apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-worker
  template:
    metadata:
      labels:
        app: task-worker
    spec:
      containers:
      - name: task-worker
        image: docker.io/yusufazaz/keda-redis-app:stable
        ports:
        - containerPort: 8080
        env:
        - name: spring.data.redis.host
          value: redis
        - name: spring.profiles.active
          value: default,worker
